services:
  pokedex-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./BACKEND:/BACKEND
      - /BACKEND/node_modules
    ports:
      - "5003:5003"

  pokedex-frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./FRONTEND:/usr/share/nginx/html
